//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba3EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unitazs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unitazs()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Unitaz { get; set; }
        public string UnitaziName { get; set; }
        public int FK_UnitazType { get; set; }
        public Nullable<decimal> UnitazPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual UnitazTypes UnitazTypes { get; set; }
    }
}
